### ISSUE TITLE
Do not repeat error message several times

### ISSUE THREAD

**Issue by eduardlavrov** [QANSIGLIERE/compare2JSONFiles#15]
Warning! Suggested keys from uniquenessJSONKeys are not acceptable
uniquenessJSONKeys: uuid,setting_name,settings_parent,id,parameter_value,resource_uri,name,product,establishment_id,short_name,product_id,code
You could use one of the following keys active,from_date,timetable_data,type,to_date

**Comment by QANSIGLIERE** [comment]
Fixed https://github.com/QANSIGLIERE/compare2JSONFiles/releases/tag/1.1.2
