### ISSUE TITLE
Could not find the uniquess key but the object contains it

### ISSUE THREAD

**Issue by eduardlavrov** [QANSIGLIERE/compare2JSONFiles#3]
Expected result: [{"updated_date":"2019-09-03T15:26:31.858168","county":null,"active":false,"id":1,"uuid":"02273278-a547-4440-a068-9776e6c82da3","district":null,"zipcode":"","created_by":"/enterprise/User/2/","state":null,"latitude":null,"line_2":"","province":null,"door":null,"updated_by":"/enterprise/User/2/","line_1":"","city_name":"","is_external":false,"country":"US","longitude":null,"building_number":null,"alias":"","created_date":"2019-09-03T15:26:31.858107","resource_uri":"/resources/Address/1/"},{"updated_date":"2020-11-17T17:50:39.414087","county":null,"active":true,"id":2,"uuid":"19991db0-a909-4ed2-bf02-6eacad99fed2","district":null,"zipcode":"11238","created_by":"/enterprise/User/1/","state":"NY","latitude":40.6871952,"line_2":"","province":null,"door":null,"updated_by":"/enterprise/User/1/","line_1":"350 Franklin Avenue","city_name":"Brooklyn","is_external":false,"country":"US","longitude":-73.9571321,"building_number":null,"alias":"","created_date":"2019-09-03T15:26:31.875880","resource_uri":"/resources/Address/2/"},{"updated_date":"2022-08-18T16:34:23.914373","county":null,"active":true,"id":34,"uuid":"bf4c397f-dd87-4ae9-bb89-f3b95d561837","district":null,"zipcode":"11238","created_by":"/enterprise/User/4/","state":"NY","latitude":40.6871952,"line_2":"","province":null,"door":null,"updated_by":"/enterprise/User/4/","line_1":"350 Franklin Avenue","city_name":"Brooklyn","is_external":false,"country":"US","longitude":-73.9571321,"building_number":null,"alias":"","created_date":"2022-08-18T16:34:23.914284","resource_uri":"/resources/Address/34/"},{"updated_date":"2022-08-18T16:35:06.296164","county":null,"active":true,"id":35,"uuid":"2a50283c-8f30-4f58-89e4-0c1884fca3c9","district":null,"zipcode":"11238","created_by":"/enterprise/User/4/","state":"NY","latitude":40.6871952,"line_2":"","province":null,"door":null,"updated_by":"/enterprise/User/4/","line_1":"350 Franklin Avenue","city_name":"Brooklyn","is_external":false,"country":"US","longitude":-73.9571321,"building_number":null,"alias":"","created_date":"2022-08-18T16:35:06.296107","resource_uri":"/resources/Address/35/"},{"updated_date":"2022-08-18T16:36:38.778654","county":null,"active":true,"id":36,"uuid":"ed4b9ca7-6a3c-4297-bcf6-cb8779fb38e3","district":null,"zipcode":"11238","created_by":"/enterprise/User/4/","state":"NY","latitude":40.6871952,"line_2":"","province":null,"door":null,"updated_by":"/enterprise/User/4/","line_1":"350 Franklin Avenue","city_name":"Brooklyn","is_external":false,"country":"US","longitude":-73.9571321,"building_number":null,"alias":"","created_date":"2022-08-18T16:36:38.778597","resource_uri":"/resources/Address/36/"},{"updated_date":"2022-08-18T16:38:01.545672","county":null,"active":true,"id":37,"uuid":"61520d78-979c-4ad3-a024-e15fce9d1e50","district":null,"zipcode":"11238","created_by":"/enterprise/User/4/","state":"NY","latitude":40.6871952,"line_2":"","province":null,"door":null,"updated_by":"/enterprise/User/4/","line_1":"350 Franklin Avenue","city_name":"Brooklyn","is_external":false,"country":"US","longitude":-73.9571321,"building_number":null,"alias":"","created_date":"2022-08-18T16:38:01.545615","resource_uri":"/resources/Address/37/"},{"updated_date":"2022-08-19T08:50:10.230424","county":null,"active":true,"id":38,"uuid":"8fb59ff0-63fd-42f3-ab6c-5c37dd964792","district":null,"zipcode":"11238","created_by":"/enterprise/User/4/","state":"NY","latitude":40.6871952,"line_2":"","province":null,"door":null,"updated_by":"/enterprise/User/4/","line_1":"350 Franklin Avenue","city_name":"Brooklyn","is_external":false,"country":"US","longitude":-73.9571321,"building_number":null,"alias":"","created_date":"2022-08-19T08:50:10.230342","resource_uri":"/resources/Address/38/"}]
        Actual result: [{"updated_date":"2019-09-03T15:26:31.858168","county":null,"active":false,"id":1,"uuid":"02273278-a547-4440-a068-9776e6c82da3","district":null,"zipcode":"","created_by":"/enterprise/User/2/","state":null,"latitude":null,"line_2":"","province":null,"door":null,"updated_by":"/enterprise/User/2/","line_1":"","city_name":"","is_external":false,"country":"US","longitude":null,"building_number":null,"alias":"","created_date":"2019-09-03T15:26:31.858107","resource_uri":"/resources/Address/1/"},{"updated_date":"2020-11-17T17:50:39.414087","county":null,"active":true,"id":2,"uuid":"19991db0-a909-4ed2-bf02-6eacad99fed2","district":null,"zipcode":"11238","created_by":"/enterprise/User/1/","state":"NY","latitude":40.6871952,"line_2":"","province":null,"door":null,"updated_by":"/enterprise/User/1/","line_1":"350 Franklin Avenue","city_name":"Brooklyn","is_external":false,"country":"US","longitude":-73.9571321,"building_number":null,"alias":"","created_date":"2019-09-03T15:26:31.875880","resource_uri":"/resources/Address/2/"},{"updated_date":"2022-08-18T16:34:23.914373","county":null,"active":true,"id":34,"uuid":"bf4c397f-dd87-4ae9-bb89-f3b95d561837","district":null,"zipcode":"11238","created_by":"/enterprise/User/4/","state":"NY","latitude":40.6871952,"line_2":"","province":null,"door":null,"updated_by":"/enterprise/User/4/","line_1":"350 Franklin Avenue","city_name":"Brooklyn","is_external":false,"country":"US","longitude":-73.9571321,"building_number":null,"alias":"","created_date":"2022-08-18T16:34:23.914284","resource_uri":"/resources/Address/34/"},{"updated_date":"2022-08-18T16:35:06.296164","county":null,"active":true,"id":35,"uuid":"2a50283c-8f30-4f58-89e4-0c1884fca3c9","district":null,"zipcode":"11238","created_by":"/enterprise/User/4/","state":"NY","latitude":40.6871952,"line_2":"","province":null,"door":null,"updated_by":"/enterprise/User/4/","line_1":"350 Franklin Avenue","city_name":"Brooklyn","is_external":false,"country":"US","longitude":-73.9571321,"building_number":null,"alias":"","created_date":"2022-08-18T16:35:06.296107","resource_uri":"/resources/Address/35/"},{"updated_date":"2022-08-18T16:36:38.778654","county":null,"active":true,"id":36,"uuid":"ed4b9ca7-6a3c-4297-bcf6-cb8779fb38e3","district":null,"zipcode":"11238","created_by":"/enterprise/User/4/","state":"NY","latitude":40.6871952,"line_2":"","province":null,"door":null,"updated_by":"/enterprise/User/4/","line_1":"350 Franklin Avenue","city_name":"Brooklyn","is_external":false,"country":"US","longitude":-73.9571321,"building_number":null,"alias":"","created_date":"2022-08-18T16:36:38.778597","resource_uri":"/resources/Address/36/"},{"updated_date":"2022-08-18T16:38:01.545672","county":null,"active":true,"id":37,"uuid":"61520d78-979c-4ad3-a024-e15fce9d1e50","district":null,"zipcode":"11238","created_by":"/enterprise/User/4/","state":"NY","latitude":40.6871952,"line_2":"","province":null,"door":null,"updated_by":"/enterprise/User/4/","line_1":"350 Franklin Avenue","city_name":"Brooklyn","is_external":false,"country":"US","longitude":-73.9571321,"building_number":null,"alias":"","created_date":"2022-08-18T16:38:01.545615","resource_uri":"/resources/Address/37/"},{"updated_date":"2022-08-19T08:50:10.230424","county":null,"active":true,"id":38,"uuid":"8fb59ff0-63fd-42f3-ab6c-5c37dd964792","district":null,"zipcode":"11238","created_by":"/enterprise/User/4/","state":"NY","latitude":40.6871952,"line_2":"","province":null,"door":null,"updated_by":"/enterprise/User/4/","line_1":"350 Franklin Avenue","city_name":"Brooklyn","is_external":false,"country":"US","longitude":-73.9571321,"building_number":null,"alias":"","created_date":"2022-08-19T08:50:10.230342","resource_uri":"/resources/Address/38/"}]
        Error: Did not found any similar item by suggested uniquenessJSONKeys key

**Comment by QANSIGLIERE** [comment]
Fixed https://github.com/QANSIGLIERE/compare2JSONFiles/commit/5b882193c5289368698589fb511e723eb90045de
