### ISSUE TITLE
Print object values in the console

### ISSUE THREAD

**Issue by eduardlavrov** [QANSIGLIERE/compare2JSONFiles#5]
Difference in expected results: [object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]
Difference in actual results: [object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]

**Comment by QANSIGLIERE** [comment]
Fixed here: https://github.com/QANSIGLIERE/compare2JSONFiles/pull/6
