### ISSUE TITLE
Non-unique items are present in Difference values

### ISSUE THREAD

**Issue by eduardlavrov** [QANSIGLIERE/compare2JSONFiles#8]
Difference in expected results: [{"updated_date":"2019-09-03T15:26:34.059840","payment_id":0,"change_label":"Other Change","capture_id":false,"updated_by":"/enterprise/User/2/","id_label":"Other Label","created_by":"/enterprise/User/2/","name":"Other","is_admin":true,"created_date":"2019-09-03T15:26:34.059795","active":true,"is_public":false,"type":0,"resource_uri":"/resources/CustomPaymentType/0/"},{"updated_date":"2019-09-03T15:26:34.059938","payment_id":1,"change_label":"Cash Change","capture_id":false,"updated_by":"/enterprise/User/2/","id_label":"Cash Label","created_by":"/enterprise/User/2/","name":"Cash","is_admin":true,"created_date":"2019-09-03T15:26:34.059911","active":true,"is_public":true,"type":0,"resource_uri":"/resources/CustomPaymentType/1/"},{"updated_date":"2019-09-03T15:26:34.060031","payment_id":2,"change_label":"Credit Change","capture_id":false,"updated_by":"/enterprise/User/2/","id_label":"Credit Label","created_by":"/enterprise/User/2/","name":"Credit","is_admin":true,"created_date":"2019-09-03T15:26:34.060006","active":true,"is_public":true,"type":1,"resource_uri":"/resources/CustomPaymentType/2/"},{"updated_date":"2019-09-03T15:26:34.060124","payment_id":3,"change_label":"Check Change","capture_id":false,"updated_by":"/enterprise/User/2/","id_label":"Check Label","created_by":"/enterprise/User/2/","name":"Check","is_admin":true,"created_date":"2019-09-03T15:26:34.060098","active":true,"is_public":true,"type":1,"resource_uri":"/resources/CustomPaymentType/3/"},{"updated_date":"2019-09-03T15:26:34.060215","payment_id":4,"change_label":"Gift Change","capture_id":false,"updated_by":"/enterprise/User/2/","id_label":"Gift Label","created_by":"/enterprise/User/2/","name":"Gift","is_admin":true,"created_date":"2019-09-03T15:26:34.060190","active":true,"is_public":true,"type":1,"resource_uri":"/resources/CustomPaymentType/4/"},{"updated_date":"2019-09-03T15:26:34.060306","payment_id":5,"change_label":"CreditManual Change","capture_id":false,"updated_by":"/enterprise/User/2/","id_label":"CreditManual Label","created_by":"/enterprise/User/2/","name":"CreditManual","is_admin":true,"created_date":"2019-09-03T15:26:34.060282","active":true,"is_public":true,"type":1,"resource_uri":"/resources/CustomPaymentType/5/"},{"updated_date":"2019-09-03T15:26:34.060398","payment_id":6,"change_label":"CreditPlus Change","capture_id":false,"updated_by":"/enterprise/User/2/","id_label":"CreditPlus Label","created_by":"/enterprise/User/2/","name":"CreditPlus","is_admin":true,"created_date":"2019-09-03T15:26:34.060373","active":true,"is_public":true,"type":1,"resource_uri":"/resources/CustomPaymentType/6/"},{"updated_date":"2019-09-03T15:26:34.060489","payment_id":7,"change_label":"LevelUp Change","capture_id":false,"updated_by":"/enterprise/User/2/","id_label":"LevelUp Label","created_by":"/enterprise/User/2/","name":"LevelUp","is_admin":true,"created_date":"2019-09-03T15:26:34.060464","active":true,"is_public":true,"type":1,"resource_uri":"/resources/CustomPaymentType/7/"},{"updated_date":"2019-09-03T15:26:34.060760","payment_id":8,"change_label":"Debit Change","capture_id":false,"updated_by":"/enterprise/User/2/","id_label":"Debit Label","created_by":"/enterprise/User/2/","name":"Debit","is_admin":true,"created_date":"2019-09-03T15:26:34.060735","active":true,"is_public":true,"type":1,"resource_uri":"/resources/CustomPaymentType/8/"},{"updated_date":"2019-09-03T15:26:34.060850","payment_id":9,"change_label":"Badge Change","capture_id":false,"updated_by":"/enterprise/User/2/","id_label":"Badge Label","created_by":"/enterprise/User/2/","name":"Badge","is_admin":true,"created_date":"2019-09-03T15:26:34.060826","active":true,"is_public":true,"type":1,"resource_uri":"/resources/CustomPaymentType/9/"},{"updated_date":"2019-09-03T15:26:34.061031","payment_id":11,"change_label":"Paypal Change","capture_id":false,"updated_by":"/enterprise/User/2/","id_label":"Paypal Label","created_by":"/enterprise/User/2/","name":"Paypal","is_admin":true,"created_date":"2019-09-03T15:26:34.061006","active":true,"is_public":true,"type":1,"resource_uri":"/resources/CustomPaymentType/11/"},{"updated_date":"2019-09-03T15:26:34.061122","payment_id":12,"change_label":"EBT Foodstamp Change","capture_id":false,"updated_by":"/enterprise/User/2/","id_label":"EBT Foodstamp Label","created_by":"/enterprise/User/2/","name":"EBT Foodstamp","is_admin":true,"created_date":"2019-09-03T15:26:34.061097","active":true,"is_public":true,"type":1,"resource_uri":"/resources/CustomPaymentType/12/"},{"updated_date":"2019-09-03T15:26:34.061302","payment_id":14,"change_label":"EBT Cash Change","capture_id":false,"updated_by":"/enterprise/User/2/","id_label":"EBT Cash Label","created_by":"/enterprise/User/2/","name":"EBT Cash","is_admin":true,"created_date":"2019-09-03T15:26:34.061278","active":true,"is_public":true,"type":1,"resource_uri":"/resources/CustomPaymentType/14/"},{"updated_date":"2019-09-03T15:26:34.061393","payment_id":15,"change_label":"Zapper Change","capture_id":false,"updated_by":"/enterprise/User/2/","id_label":"Zapper Label","created_by":"/enterprise/User/2/","name":"Zapper","is_admin":true,"created_date":"2019-09-03T15:26:34.061369","active":true,"is_public":true,"type":1,"resource_uri":"/resources/CustomPaymentType/15/"},{"updated_date":"2019-09-03T15:26:34.061483","payment_id":16,"change_label":"SSMC Change","capture_id":false,"updated_by":"/enterprise/User/2/","id_label":"SSMC Label","created_by":"/enterprise/User/2/","name":"SSMC","is_admin":true,"created_date":"2019-09-03T15:26:34.061458","active":true,"is_public":true,"type":1,"resource_uri":"/resources/CustomPaymentType/16/"},{"updated_date":"2019-09-03T15:26:34.061574","payment_id":17,"change_label":"SaleLossDriveOff Change","capture_id":false,"updated_by":"/enterprise/User/2/","id_label":"SaleLossDriveOff Label","created_by":"/enterprise/User/2/","name":"SaleLossDriveOff","is_admin":true,"created_date":"2019-09-03T15:26:34.061549","active":true,"is_public":false,"type":1,"resource_uri":"/resources/CustomPaymentType/17/"},{"updated_date":"2019-09-03T15:26:34.061664","payment_id":18,"change_label":"FleetCard Change","capture_id":false,"updated_by":"/enterprise/User/2/","id_label":"FleetCard Label","created_by":"/enterprise/User/2/","name":"FleetCard","is_admin":true,"created_date":"2019-09-03T15:26:34.061639","active":true,"is_public":true,"type":1,"resource_uri":"/resources/CustomPaymentType/18/"},{"updated_date":"2019-09-03T15:26:34.061754","payment_id":19,"change_label":"FleetCardManual Change","capture_id":false,"updated_by":"/enterprise/User/2/","id_label":"FleetCardManual Label","created_by":"/enterprise/User/2/","name":"FleetCardManual","is_admin":true,"created_date":"2019-09-03T15:26:34.061729","active":true,"is_public":true,"type":1,"resource_uri":"/resources/CustomPaymentType/19/"},{"updated_date":"2019-09-03T15:26:34.061844","payment_id":20,"change_label":"WoraPay Change","capture_id":false,"updated_by":"/enterprise/User/2/","id_label":"WoraPay Label","created_by":"/enterprise/User/2/","name":"WoraPay","is_admin":true,"created_date":"2019-09-03T15:26:34.061820","active":true,"is_public":true,"type":1,"resource_uri":"/resources/CustomPaymentType/20/"},{"updated_date":"2019-09-03T15:26:34.061935","payment_id":21,"change_label":"Store Credit Change","capture_id":false,"updated_by":"/enterprise/User/2/","id_label":"Store Credit","created_by":"/enterprise/User/2/","name":"Store Credit","is_admin":true,"created_date":"2019-09-03T15:26:34.061910","active":true,"is_public":true,"type":1,"resource_uri":"/resources/CustomPaymentType/21/"},{"updated_date":"2019-09-03T15:26:34.062027","payment_id":22,"change_label":"Como Budget Change","capture_id":false,"updated_by":"/enterprise/User/2/","id_label":"Como Budget","created_by":"/enterprise/User/2/","name":"Como Budget","is_admin":true,"created_date":"2019-09-03T15:26:34.062002","active":true,"is_public":true,"type":1,"resource_uri":"/resources/CustomPaymentType/22/"},{"updated_date":"2019-09-03T15:26:34.062118","payment_id":23,"change_label":"LoyaltyPlant Change","capture_id":false,"updated_by":"/enterprise/User/2/","id_label":"LoyaltyPlant","created_by":"/enterprise/User/2/","name":"LoyaltyPlant","is_admin":true,"created_date":"2019-09-03T15:26:34.062093","active":true,"is_public":true,"type":1,"resource_uri":"/resources/CustomPaymentType/23/"},{"updated_date":"2019-09-03T15:26:34.062209","payment_id":24,"change_label":"Voucher Change","capture_id":false,"updated_by":"/enterprise/User/2/","id_label":"Voucher","created_by":"/enterprise/User/2/","name":"Voucher","is_admin":true,"created_date":"2019-09-03T15:26:34.062184","active":true,"is_public":true,"type":1,"resource_uri":"/resources/CustomPaymentType/24/"},{"updated_date":"2019-09-03T15:26:34.062299","payment_id":25,"change_label":"Rabbit Change","capture_id":false,"updated_by":"/enterprise/User/2/","id_label":"Rabbit Label","created_by":"/enterprise/User/2/","name":"Rabbit","is_admin":true,"created_date":"2019-09-03T15:26:34.062274","active":true,"is_public":true,"type":1,"resource_uri":"/resources/CustomPaymentType/25/"},{"updated_date":"2019-09-03T15:26:34.062389","payment_id":26,"change_label":"LinePay Change","capture_id":false,"updated_by":"/enterprise/User/2/","id_label":"LinePay Label","created_by":"/enterprise/User/2/","name":"LinePay","is_admin":true,"created_date":"2019-09-03T15:26:34.062364","active":true,"is_public":false,"type":1,"resource_uri":"/resources/CustomPaymentType/26/"},{"updated_date":"2019-09-03T15:26:34.062479","payment_id":27,"change_label":"Wechat/AliPay Change","capture_id":false,"updated_by":"/enterprise/User/2/","id_label":"Wechat/AliPay Label","created_by":"/enterprise/User/2/","name":"Wechat/AliPay","is_admin":true,"created_date":"2019-09-03T15:26:34.062455","active":true,"is_public":false,"type":1,"resource_uri":"/resources/CustomPaymentType/27/"},{"updated_date":"2019-09-03T15:26:34.062660","payment_id":29,"change_label":"NETS Change","capture_id":false,"updated_by":"/enterprise/User/2/","id_label":"NETS Label","created_by":"/enterprise/User/2/","name":"NETS","is_admin":true,"created_date":"2019-09-03T15:26:34.062636","active":true,"is_public":true,"type":1,"resource_uri":"/resources/CustomPaymentType/29/"},{"updated_date":"2019-09-03T15:26:34.062750","payment_id":30,"change_label":"LevelUp Gift Change","capture_id":false,"updated_by":"/enterprise/User/2/","id_label":"LevelUp Gift Label","created_by":"/enterprise/User/2/","name":"LevelUp Gift","is_admin":true,"created_date":"2019-09-03T15:26:34.062725","active":true,"is_public":true,"type":1,"resource_uri":"/resources/CustomPaymentType/30/"},{"updated_date":"2021-04-26T09:28:29.583013","payment_id":31,"change_label":"SMS Change","capture_id":false,"updated_by":"/enterprise/User/2/","id_label":"SMS Label","created_by":"/enterprise/User/2/","name":"SMS","is_admin":true,"created_date":"2021-04-26T09:28:29.583013","active":true,"is_public":true,"type":1,"resource_uri":"/resources/CustomPaymentType/31/"},{"updated_date":"2019-09-03T15:26:34.060579","payment_id":101,"change_label":"ServiceCharge Change","capture_id":false,"updated_by":"/enterprise/User/2/","id_label":"ServiceCharge Label","created_by":"/enterprise/User/2/","name":"ServiceCharge","is_admin":true,"created_date":"2019-09-03T15:26:34.060555","active":true,"is_public":false,"type":1,"resource_uri":"/resources/CustomPaymentType/101/"},{"updated_date":"2019-09-03T15:26:34.060670","payment_id":102,"change_label":"Deposit Change","capture_id":false,"updated_by":"/enterprise/User/2/","id_label":"Deposit Label","created_by":"/enterprise/User/2/","name":"Deposit","is_admin":true,"created_date":"2019-09-03T15:26:34.060645","active":true,"is_public":false,"type":1,"resource_uri":"/resources/CustomPaymentType/102/"},{"updated_date":"2020-11-05T17:02:27.366882","payment_id":200,"change_label":"LevelUp","capture_id":false,"updated_by":"/enterprise/User/4/","id_label":"LevelUp","created_by":"/enterprise/User/4/","name":"LevelUpCustom","is_admin":false,"created_date":"2020-11-05T17:02:27.366755","active":true,"is_public":true,"type":1,"resource_uri":"/resources/CustomPaymentType/200/"}]
Difference in actual results: [{"updated_date":"2019-09-03T15:26:34.059840","payment_id":0,"change_label":"Other Change","capture_id":false,"updated_by":"/enterprise/User/2/","id_label":"Other Label","created_by":"/enterprise/User/2/","name":"Other","is_admin":true,"created_date":"2019-09-03T15:26:34.059795","active":true,"is_public":false,"type":0,"resource_uri":"/resources/CustomPaymentType/0/"},{"updated_date":"2019-09-03T15:26:34.059938","payment_id":1,"change_label":"Cash Change","capture_id":false,"updated_by":"/enterprise/User/2/","id_label":"Cash Label","created_by":"/enterprise/User/2/","name":"Cash","is_admin":true,"created_date":"2019-09-03T15:26:34.059911","active":true,"is_public":true,"type":0,"resource_uri":"/resources/CustomPaymentType/1/"},{"updated_date":"2019-09-03T15:26:34.060031","payment_id":2,"change_label":"Credit Change","capture_id":false,"updated_by":"/enterprise/User/2/","id_label":"Credit Label","created_by":"/enterprise/User/2/","name":"Credit","is_admin":true,"created_date":"2019-09-03T15:26:34.060006","active":true,"is_public":true,"type":1,"resource_uri":"/resources/CustomPaymentType/2/"},{"updated_date":"2019-09-03T15:26:34.060124","payment_id":3,"change_label":"Check Change","capture_id":false,"updated_by":"/enterprise/User/2/","id_label":"Check Label","created_by":"/enterprise/User/2/","name":"Check","is_admin":true,"created_date":"2019-09-03T15:26:34.060098","active":true,"is_public":true,"type":1,"resource_uri":"/resources/CustomPaymentType/3/"},{"updated_date":"2019-09-03T15:26:34.060215","payment_id":4,"change_label":"Gift Change","capture_id":false,"updated_by":"/enterprise/User/2/","id_label":"Gift Label","created_by":"/enterprise/User/2/","name":"Gift","is_admin":true,"created_date":"2019-09-03T15:26:34.060190","active":true,"is_public":true,"type":1,"resource_uri":"/resources/CustomPaymentType/4/"},{"updated_date":"2019-09-03T15:26:34.060306","payment_id":5,"change_label":"CreditManual Change","capture_id":false,"updated_by":"/enterprise/User/2/","id_label":"CreditManual Label","created_by":"/enterprise/User/2/","name":"CreditManual","is_admin":true,"created_date":"2019-09-03T15:26:34.060282","active":true,"is_public":true,"type":1,"resource_uri":"/resources/CustomPaymentType/5/"},{"updated_date":"2019-09-03T15:26:34.060398","payment_id":6,"change_label":"CreditPlus Change","capture_id":false,"updated_by":"/enterprise/User/2/","id_label":"CreditPlus Label","created_by":"/enterprise/User/2/","name":"CreditPlus","is_admin":true,"created_date":"2019-09-03T15:26:34.060373","active":true,"is_public":true,"type":1,"resource_uri":"/resources/CustomPaymentType/6/"},{"updated_date":"2019-09-03T15:26:34.060489","payment_id":7,"change_label":"LevelUp Change","capture_id":false,"updated_by":"/enterprise/User/2/","id_label":"LevelUp Label","created_by":"/enterprise/User/2/","name":"LevelUp","is_admin":true,"created_date":"2019-09-03T15:26:34.060464","active":true,"is_public":true,"type":1,"resource_uri":"/resources/CustomPaymentType/7/"},{"updated_date":"2019-09-03T15:26:34.060760","payment_id":8,"change_label":"Debit Change","capture_id":false,"updated_by":"/enterprise/User/2/","id_label":"Debit Label","created_by":"/enterprise/User/2/","name":"Debit","is_admin":true,"created_date":"2019-09-03T15:26:34.060735","active":true,"is_public":true,"type":1,"resource_uri":"/resources/CustomPaymentType/8/"},{"updated_date":"2019-09-03T15:26:34.060850","payment_id":9,"change_label":"Badge Change","capture_id":false,"updated_by":"/enterprise/User/2/","id_label":"Badge Label","created_by":"/enterprise/User/2/","name":"Badge","is_admin":true,"created_date":"2019-09-03T15:26:34.060826","active":true,"is_public":true,"type":1,"resource_uri":"/resources/CustomPaymentType/9/"},{"updated_date":"2019-09-03T15:26:34.061122","payment_id":12,"change_label":"EBT Foodstamp Change","capture_id":false,"updated_by":"/enterprise/User/2/","id_label":"EBT Foodstamp Label","created_by":"/enterprise/User/2/","name":"EBT Foodstamp","is_admin":true,"created_date":"2019-09-03T15:26:34.061097","active":true,"is_public":true,"type":1,"resource_uri":"/resources/CustomPaymentType/12/"},{"updated_date":"2019-09-03T15:26:34.061302","payment_id":14,"change_label":"EBT Cash Change","capture_id":false,"updated_by":"/enterprise/User/2/","id_label":"EBT Cash Label","created_by":"/enterprise/User/2/","name":"EBT Cash","is_admin":true,"created_date":"2019-09-03T15:26:34.061278","active":true,"is_public":true,"type":1,"resource_uri":"/resources/CustomPaymentType/14/"},{"updated_date":"2019-09-03T15:26:34.061393","payment_id":15,"change_label":"Zapper Change","capture_id":false,"updated_by":"/enterprise/User/2/","id_label":"Zapper Label","created_by":"/enterprise/User/2/","name":"Zapper","is_admin":true,"created_date":"2019-09-03T15:26:34.061369","active":true,"is_public":true,"type":1,"resource_uri":"/resources/CustomPaymentType/15/"},{"updated_date":"2019-09-03T15:26:34.061483","payment_id":16,"change_label":"SSMC Change","capture_id":false,"updated_by":"/enterprise/User/2/","id_label":"SSMC Label","created_by":"/enterprise/User/2/","name":"SSMC","is_admin":true,"created_date":"2019-09-03T15:26:34.061458","active":true,"is_public":true,"type":1,"resource_uri":"/resources/CustomPaymentType/16/"},{"updated_date":"2019-09-03T15:26:34.061574","payment_id":17,"change_label":"SaleLossDriveOff Change","capture_id":false,"updated_by":"/enterprise/User/2/","id_label":"SaleLossDriveOff Label","created_by":"/enterprise/User/2/","name":"SaleLossDriveOff","is_admin":true,"created_date":"2019-09-03T15:26:34.061549","active":true,"is_public":false,"type":1,"resource_uri":"/resources/CustomPaymentType/17/"},{"updated_date":"2019-09-03T15:26:34.061664","payment_id":18,"change_label":"FleetCard Change","capture_id":false,"updated_by":"/enterprise/User/2/","id_label":"FleetCard Label","created_by":"/enterprise/User/2/","name":"FleetCard","is_admin":true,"created_date":"2019-09-03T15:26:34.061639","active":true,"is_public":true,"type":1,"resource_uri":"/resources/CustomPaymentType/18/"},{"updated_date":"2019-09-03T15:26:34.061754","payment_id":19,"change_label":"FleetCardManual Change","capture_id":false,"updated_by":"/enterprise/User/2/","id_label":"FleetCardManual Label","created_by":"/enterprise/User/2/","name":"FleetCardManual","is_admin":true,"created_date":"2019-09-03T15:26:34.061729","active":true,"is_public":true,"type":1,"resource_uri":"/resources/CustomPaymentType/19/"},{"updated_date":"2019-09-03T15:26:34.061844","payment_id":20,"change_label":"WoraPay Change","capture_id":false,"updated_by":"/enterprise/User/2/","id_label":"WoraPay Label","created_by":"/enterprise/User/2/","name":"WoraPay","is_admin":true,"created_date":"2019-09-03T15:26:34.061820","active":true,"is_public":true,"type":1,"resource_uri":"/resources/CustomPaymentType/20/"},{"updated_date":"2019-09-03T15:26:34.061935","payment_id":21,"change_label":"Store Credit Change","capture_id":false,"updated_by":"/enterprise/User/2/","id_label":"Store Credit","created_by":"/enterprise/User/2/","name":"Store Credit","is_admin":true,"created_date":"2019-09-03T15:26:34.061910","active":true,"is_public":true,"type":1,"resource_uri":"/resources/CustomPaymentType/21/"},{"updated_date":"2019-09-03T15:26:34.062027","payment_id":22,"change_label":"Como Budget Change","capture_id":false,"updated_by":"/enterprise/User/2/","id_label":"Como Budget","created_by":"/enterprise/User/2/","name":"Como Budget","is_admin":true,"created_date":"2019-09-03T15:26:34.062002","active":true,"is_public":true,"type":1,"resource_uri":"/resources/CustomPaymentType/22/"},{"updated_date":"2019-09-03T15:26:34.062118","payment_id":23,"change_label":"LoyaltyPlant Change","capture_id":false,"updated_by":"/enterprise/User/2/","id_label":"LoyaltyPlant","created_by":"/enterprise/User/2/","name":"LoyaltyPlant","is_admin":true,"created_date":"2019-09-03T15:26:34.062093","active":true,"is_public":true,"type":1,"resource_uri":"/resources/CustomPaymentType/23/"},{"updated_date":"2019-09-03T15:26:34.062209","payment_id":24,"change_label":"Voucher Change","capture_id":false,"updated_by":"/enterprise/User/2/","id_label":"Voucher","created_by":"/enterprise/User/2/","name":"Voucher","is_admin":true,"created_date":"2019-09-03T15:26:34.062184","active":true,"is_public":true,"type":1,"resource_uri":"/resources/CustomPaymentType/24/"},{"updated_date":"2019-09-03T15:26:34.062299","payment_id":25,"change_label":"Rabbit Change","capture_id":false,"updated_by":"/enterprise/User/2/","id_label":"Rabbit Label","created_by":"/enterprise/User/2/","name":"Rabbit","is_admin":true,"created_date":"2019-09-03T15:26:34.062274","active":true,"is_public":true,"type":1,"resource_uri":"/resources/CustomPaymentType/25/"},{"updated_date":"2019-09-03T15:26:34.062389","payment_id":26,"change_label":"LinePay Change","capture_id":false,"updated_by":"/enterprise/User/2/","id_label":"LinePay Label","created_by":"/enterprise/User/2/","name":"LinePay","is_admin":true,"created_date":"2019-09-03T15:26:34.062364","active":true,"is_public":false,"type":1,"resource_uri":"/resources/CustomPaymentType/26/"},{"updated_date":"2019-09-03T15:26:34.062479","payment_id":27,"change_label":"Wechat/AliPay Change","capture_id":false,"updated_by":"/enterprise/User/2/","id_label":"Wechat/AliPay Label","created_by":"/enterprise/User/2/","name":"Wechat/AliPay","is_admin":true,"created_date":"2019-09-03T15:26:34.062455","active":true,"is_public":false,"type":1,"resource_uri":"/resources/CustomPaymentType/27/"},{"updated_date":"2019-09-03T15:26:34.062660","payment_id":29,"change_label":"NETS Change","capture_id":false,"updated_by":"/enterprise/User/2/","id_label":"NETS Label","created_by":"/enterprise/User/2/","name":"NETS","is_admin":true,"created_date":"2019-09-03T15:26:34.062636","active":true,"is_public":true,"type":1,"resource_uri":"/resources/CustomPaymentType/29/"},{"updated_date":"2019-09-03T15:26:34.062750","payment_id":30,"change_label":"LevelUp Gift Change","capture_id":false,"updated_by":"/enterprise/User/2/","id_label":"LevelUp Gift Label","created_by":"/enterprise/User/2/","name":"LevelUp Gift","is_admin":true,"created_date":"2019-09-03T15:26:34.062725","active":true,"is_public":true,"type":1,"resource_uri":"/resources/CustomPaymentType/30/"},{"updated_date":"2021-04-26T09:28:29.583013","payment_id":31,"change_label":"SMS Change","capture_id":false,"updated_by":"/enterprise/User/2/","id_label":"SMS Label","created_by":"/enterprise/User/2/","name":"SMS","is_admin":true,"created_date":"2021-04-26T09:28:29.583013","active":true,"is_public":true,"type":1,"resource_uri":"/resources/CustomPaymentType/31/"},{"updated_date":"2019-09-03T15:26:34.060579","payment_id":101,"change_label":"ServiceCharge Change","capture_id":false,"updated_by":"/enterprise/User/2/","id_label":"ServiceCharge Label","created_by":"/enterprise/User/2/","name":"ServiceCharge","is_admin":true,"created_date":"2019-09-03T15:26:34.060555","active":true,"is_public":false,"type":1,"resource_uri":"/resources/CustomPaymentType/101/"},{"updated_date":"2019-09-03T15:26:34.060670","payment_id":102,"change_label":"Deposit Change","capture_id":false,"updated_by":"/enterprise/User/2/","id_label":"Deposit Label","created_by":"/enterprise/User/2/","name":"Deposit","is_admin":true,"created_date":"2019-09-03T15:26:34.060645","active":true,"is_public":false,"type":1,"resource_uri":"/resources/CustomPaymentType/102/"},{"updated_date":"2020-11-05T17:02:27.366882","payment_id":200,"change_label":"LevelUp","capture_id":false,"updated_by":"/enterprise/User/4/","id_label":"LevelUp","created_by":"/enterprise/User/4/","name":"LevelUpCustom","is_admin":false,"created_date":"2020-11-05T17:02:27.366755","active":true,"is_public":true,"type":1,"resource_uri":"/resources/CustomPaymentType/200/"}]

**Comment by QANSIGLIERE** [comment]
Solved https://github.com/QANSIGLIERE/compare2JSONFiles/pull/9
